
version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"

  flask:
    build:
      context: ./app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - minio
      - db
    environment:
      - FLASK_APP=flask_server.py  # Ensure this matches your Flask application file
      - DB_HOST=db
      - DB_NAME=database
      - DB_USER=admin
      - DB_PASSWORD=password
    command: ["flask", "run", "--host=0.0.0.0"]

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  generator:
    build:
      context: ./app
    depends_on:
      - flask  # Ensure the Flask service is ready before running the generator
    command: python generator.py  # This will run the data generator script

volumes:
  pg_data:
